//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Ltl.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LtlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface ILtlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LtlParser.ltl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLtl([NotNull] LtlParser.LtlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LtlParser.ltl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLtl([NotNull] LtlParser.LtlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LtlParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConjunction([NotNull] LtlParser.ConjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LtlParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConjunction([NotNull] LtlParser.ConjunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LtlParser.binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinary([NotNull] LtlParser.BinaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LtlParser.binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinary([NotNull] LtlParser.BinaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LtlParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary([NotNull] LtlParser.UnaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LtlParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary([NotNull] LtlParser.UnaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LtlParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegation([NotNull] LtlParser.NegationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LtlParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegation([NotNull] LtlParser.NegationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LtlParser.proposition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProposition([NotNull] LtlParser.PropositionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LtlParser.proposition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProposition([NotNull] LtlParser.PropositionContext context);
}
